version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/nicolium"
      - "/packages/nicolium-website"
      - "/packages/pl-api"
      - "/packages/pl-hooks"
      - "/packages/website"
    schedule:
      interval: "weekly"
