site_name: Nicolium (formerly pl-fe) Documentation
site_url: https://pl.mkljczk.pl/docs/
theme:
  name: material
  language: en
  font: false
  features:
    - header.autohide
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
plugins:
  - search:
      lang: en
  - include-markdown
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
