packages:
  - 'packages/*'
allowBuilds:
  core-js: false
  esbuild: false
  sharp: false
minimumReleaseAgeExclude:
  - '@typescript/native-preview-darwin-arm64@7.0.0-dev.20260616.1'
  - '@typescript/native-preview-darwin-x64@7.0.0-dev.20260616.1'
  - '@typescript/native-preview-linux-arm64@7.0.0-dev.20260616.1'
  - '@typescript/native-preview-linux-arm@7.0.0-dev.20260616.1'
  - '@typescript/native-preview-linux-x64@7.0.0-dev.20260616.1'
  - '@typescript/native-preview-win32-arm64@7.0.0-dev.20260616.1'
  - '@typescript/native-preview-win32-x64@7.0.0-dev.20260616.1'
  - '@typescript/native-preview@7.0.0-dev.20260616.1'
overrides:
  "@babel/runtime": ^7.26.10
  glob-parent: ^6.0.2
  immutable: ^5.1.8
  js-yaml: ^4.3.0
  lodash: ^4.18.1
  svgo: ^4.0.2