version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:24.12.0
    steps:
      - checkout
      - run:
          name: Install pl-api deps
          working_directory: packages/pl-api
          command: pnpm install
      - run:
          name: Build pl-api
          working_directory: packages/pl-api
          command: pnpm run build
      - run:
          name: Install Nicolium deps
          working_directory: packages/nicolium
          command: pnpm install
      - run:
          name: Build Nicolium
          working_directory: packages/nicolium
          command: pnpm run build
      - run:
          name: Install Vercel CLI
          command: sudo npm install -g vercel
      - run:
          working_directory: packages/nicolium
          name: Deploy to Vercel
          command: vercel deploy --token $VERCEL_TOKEN --prod=false --confirm --name pl-fe

workflows:
  deploy_on_pr:
    jobs:
      - deploy
