import { Navigate } from '@tanstack/react-router';
import React, { useState } from 'react';
import { FormattedMessage, defineMessages, useIntl } from 'react-intl';

import { BigCard } from '@/components/ui/big-card';
import Card, { CardBody, CardHeader, CardTitle } from '@/components/ui/card';
import Form from '@/components/ui/form';
import FormActions from '@/components/ui/form-actions';
import FormGroup from '@/components/ui/form-group';
import Input from '@/components/ui/input';
import { useAuthActions } from '@/stores/auth';

const messages = defineMessages({
  otpLoginFail: { id: 'login.otp_log_in.fail', defaultMessage: 'Invalid code, please try again.' },
});

interface IOtpAuthForm {
  mfa_token: string;
  small?: boolean;
}

const OtpAuthForm: React.FC<IOtpAuthForm> = ({ mfa_token: mfaToken, small }) => {
  const intl = useIntl();
  const { verifyOtp, verifyCredentials, switchAccount } = useAuthActions();

  const [isLoading, setIsLoading] = useState(false);
  const [shouldRedirect, setShouldRedirect] = useState(false);
  const [codeError, setCodeError] = useState<string | boolean>('');

  const getFormData = (form: HTMLFormElement) =>
    Object.fromEntries(
      Array.from(form).map((i) => [(i as HTMLInputElement).name, (i as HTMLInputElement).value]),
    );

  const handleSubmit = (event: React.SubmitEvent<HTMLFormElement>) => {
    const { code } = getFormData(event.target);
    verifyOtp(code, mfaToken)
      .then(({ access_token }) => {
        setCodeError(false);
        return verifyCredentials(access_token);
      })
      .then((account) => {
        setShouldRedirect(true);
        return switchAccount(account);
      })
      .catch(() => {
        setIsLoading(false);
        setCodeError(true);
      });
    setIsLoading(true);
    event.preventDefault();
  };

  if (shouldRedirect) return <Navigate to='/' replace />;

  const form = (
    <Form className='otp-auth-form' onSubmit={handleSubmit}>
      <FormGroup
        labelText={
          <FormattedMessage id='login.fields.otp_code.label' defaultMessage='Two-factor code:' />
        }
        hintText={
          <FormattedMessage
            id='login.fields.otp_code.hint'
            defaultMessage='Enter the two-factor code generated by your phone app or use one of your recovery codes'
          />
        }
        errors={codeError ? [intl.formatMessage(messages.otpLoginFail)] : []}
      >
        <Input name='code' type='text' autoComplete='one-time-code' autoFocus required />
      </FormGroup>

      <FormActions>
        <button type='submit' disabled={isLoading}>
          <FormattedMessage id='login.sign_in' defaultMessage='Sign in' />
        </button>
      </FormActions>
    </Form>
  );

  if (small) {
    return (
      <Card>
        <CardHeader>
          <CardTitle
            title={<FormattedMessage id='login.otp_log_in' defaultMessage='OTP Login' />}
          />
        </CardHeader>
        <CardBody>{form}</CardBody>
      </Card>
    );
  }

  return (
    <BigCard title={<FormattedMessage id='login.otp_log_in' defaultMessage='OTP Login' />}>
      {form}
    </BigCard>
  );
};

export { OtpAuthForm as default };
